AWSTemplateFormatVersion: '2010-09-09'
Description: Provision an Amazon EKS cluster, a managed node group, and EKS add-ons

Parameters:
  ClusterName:
    Type: String
    Default: acit-demo-eks-cluster
    Description: Name of the EKS cluster

  KubernetesVersion:
    Type: String
    Default: "1.32"
    Description: EKS Kubernetes version

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnets across multiple AZs

  ClusterAdminRoleArn:
    Type: String
    Description: IAM Role ARN for EKS control plane

  NodeInstanceRoleArn:
    Type: String
    Description: IAM Role ARN for worker nodes

  NodeGroupName:
    Type: String
    Default: acit-nodegroup
    Description: Name of the EKS managed node group

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type for the node group

  DesiredCapacity:
    Type: Number
    Default: 2

  MinSize:
    Type: Number
    Default: 1

  MaxSize:
    Type: Number
    Default: 4

Resources:

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !Ref ClusterAdminRoleArn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPrivateAccess: false
        EndpointPublicAccess: true

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Ref NodeGroupName
      NodeRole: !Ref NodeInstanceRoleArn
      Subnets: !Ref SubnetIds
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
      AmiType: AmiType: AL2023_x86_64_STANDARD
      InstanceTypes:
        - !Ref InstanceType
      DiskSize: 20
      Tags:
        Project: acit-lab

  VpcCniAddon:
    Type: AWS::EKS::Addon
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      AddonName: vpc-cni
      ResolveConflicts: OVERWRITE

  CoreDnsAddon:
    Type: AWS::EKS::Addon
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      AddonName: coredns
      ResolveConflicts: OVERWRITE

  KubeProxyAddon:
    Type: AWS::EKS::Addon
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      AddonName: kube-proxy
      ResolveConflicts: OVERWRITE

Outputs:
  ClusterName:
    Description: The name of the EKS cluster
    Value: !Ref EKSCluster

  ClusterEndpoint:
    Description: API server endpoint
    Value: !GetAtt EKSCluster.Endpoint

  NodeGroupName:
    Description: Managed node group name
    Value: !Ref EKSNodeGroup

  VpcCniAddon:
    Description: VPC CNI add-on reference
    Value: !Ref VpcCniAddon
